### PR TITLE
test: introduce jest testing.

### PR DESCRIPTION
**Pull request by CameronRushton**
**Description**
Added jest testing with a basic test to kick it off

### CODE REVIEW

**Comment by derberg** [comment]
- for test coverage, we want to use coveralls in all the projects. I just enabled it for this repo. Here are some further instructions from Jonas that you can follow https://github.com/asyncapi/.github/issues/30. I recommend working on it on a separate PR to make PRs as complex as possible,
- long term consider snapshot testing if you want to make sure generated java files are correct -> https://github.com/asyncapi/generator/blob/master/test/integration.test.js#L29
- why renaming eslint config file, we try to be consistent with those when possible across repos
- is husky necessary? pre commit actions always take time and interfere with development flow when the developer is used to commit often. We try to avoid such configurations in such open projects. In all our 50 repos we have it in just 2. In one project to enforce `dist` generation as this part is not automated yet, and another has it as a left over from when it was donated to asyncapi and automation was not there yet.

**Review by derberg — CHANGES_REQUESTED** [review]
Hey @CameronRushton 
thanks for the contribution, left some comments.

are you here for longer or is this rather an onboarding job from Solace?

**Comment by CameronRushton** [comment]
Thanks @derberg 
I think I'll be helping out with this project when I can for the foreseeable future.

I'll add coverage reports in another PR in that case.
I'll also see about using snapshots. Thanks for the linked example.
I added .yaml to eslintrc so that VS Code has proper highlighting but perhaps it's not the file's problem, it's my workspace configuration's problem, yeah? I do want to stay consistent with the other projects here.

I'd like to keep the pre-commit actions. If a dev doesn't want to run it they can use `--no-verify` on their commit and if it takes too long to write that out, I would recommend creating an alias in their bashrc or something. Though this isn't a hill I care to die on since the actions should run in the PR anyway. I'll remove it and keep an eye on future PRs' test results to gauge whether or not it should be added.

**Comment by derberg** [comment]
@CameronRushton awesome stuff, welcome, great to see more folks from Solace helping out! We are pretty active on Slack so when you needs some quick support feel free to ping us in the tooling channel.

And thanks for being opened to my comments 🙏🏼

**Comment by CameronRushton** [comment]
Do I need to do something to tell sonar to ignore that security hotspot?
It's also hard to tell if tests are running so I'm not sure if it's set up right. I dont remember seeing status being reported before.

**Comment by derberg** [comment]
@CameronRushton create [this file](https://github.com/asyncapi/modelina/blob/676726ac6385afbd901a5ebc0c5ad0c2a1064499/sonar-project.properties) and specify the failing file under the following key -> `sonar.exclusions`. This will exclude any check by sonar for this file, which is ok as it is test

**Review by damaru-inc — DISMISSED** [review]
Thanks a lot for this Cameron! Works great.

**Comment by CameronRushton** [comment]
The test files seem to be excluded from sonar properly when running sonar locally. I don't know why it's still upset here.

**Comment by derberg** [comment]
maybe try to provide the exact path to the file? like https://github.com/asyncapi/modelina/blob/master/sonar-project.properties

also try https://www.baeldung.com/sonar-exclude-violations#using-nosonar if above doesn't work

**Review by derberg — DISMISSED** [review]
This is a great addition @CameronRushton !

**Comment by derberg** [comment]
@CameronRushton there is some cleanup in tests needed

**Comment by CameronRushton** [comment]
Turns out I made a mistake changing the for each loop to a lambda. The promise to grab the generated files didn't resolve until after jest was finished which made it think there were no snapshots.

**Comment by derberg** [comment]
@CameronRushton I think you will have to update snapshots as I had to merge master otherwise outdated PR can't be merged and there were some changes in master that influenced the snapshot

**Review by damaru-inc — APPROVED** [review]

**Pull request merged**
