### PR TITLE
fix: Update Spring & Solace Versions

### PR DESCRIPTION
**Pull request by Mrc0113**
Update Versions: 
* Solace Binder had some important bug fixes as part of `solace-spring-cloud` v1.1.1 release
* Updated to latest Spring Boot, Spring Cloud & Cloud Stream while at it!

### CODE REVIEW

**Comment by derberg** [comment]
I'm not a fan of this approach to have `Solace` specific downloads in the code, since several releases you can pass defaults in the configuration of the template, you just add `default` parameter here https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/package.json#L106-L109. Did you consider this?

**Comment by Mrc0113** [comment]
Hi @derberg, yea I think it's a balance. First I want to say I am updating the versions for Spring Boot, Spring Cloud, Spring Cloud Stream and Solace. You can of course set all of these things using the parameters that are exposed but it's not ideal for someone to have to go research the version they want for all 4 of those. 

What I would suggest is that going forward when major releases are made we update the version here as well. This will in theory provide a good experience where developers would have the latest features available in the framework/binders. 

That said, I would like to still merge this release as the Solace binder v1.1.1 had an important fix and devs shouldn't use v1.1.0. 

Thoughts?

**Comment by derberg** [comment]
@Mrc0113 what I said is that these hardcoded values should be moved from code to config like this https://github.com/asyncapi/java-spring-template/blob/master/package.json#L113. Defaults are still important but we should not hardcode them in the template. Nevertheless I know it is not something you should fix withing this PR. Could you create a followup issue please?

**Comment by Mrc0113** [comment]
My bad @derberg, I definitely mis-understood what you were saying there. Sure I'll open a separate issue for that 👍

**Pull request merged**
