### PR TITLE
Added a useful resource

### PR DESCRIPTION
**Pull request by jivan84**
Hey, I've added a useful reference link for the java package, I think this will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.

**Description**

- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Review by MichaelDavisSolace — COMMENTED** [review]
Sorry, it isn't appropriate to add links like this here. I wouldn't mind a link to the official Java documentation from Oracle or something, but not private companies.

**Comment by CameronRushton** [comment]
Perhaps this link is more suitable https://docs.oracle.com/javase/tutorial/java/package/packages.html
Though, I would think a package is a more commonly known thing than the other parameters, so I think it's more worthwhile to provide resources for some of those, instead or in addition, if any official docs exist that aren't behind a privately controlled link.

**Comment by damaru-inc** [comment]
I agree. It would be odd for someone to be using this tool without knowing what Java packages are. I don't think this is the place to provide links to help brand new Java developers.

**Comment by CameronRushton** [comment]
Judging from OP's history, they clearly have no intention of thoughtfully contributing to the repo. Closing as spam.

**Comment by jivan84** [comment]
It may be that the link is not suitable for your repo for now but, It is not spam. Thanks, brother.

**Pull request closed without merging**
