### PR TITLE
fix: generate correct fields using both type and format part from data type formats

### LINKED ISSUE #57: Date-time format is not supported
---
name: Bug Date-time format is not supported
labels: bug
---

#### Describe the bug
Date-time format is not supported

#### How to Reproduce
Generating code with date-time format at some of theirs fields

- asyncapi file example

```asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        $ref: '#/components/messages/lightMeasured'
    subscribe:
      operationId: updateLightMeasurement
      message:
        $ref: '#/components/messages/lightMeasured'
components:
  messages:
    lightMeasured:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      payload:
        $ref: "#/components/schemas/lightMeasuredPayload"
  schemas:
    lightMeasuredPayload:
      type: object
      properties:
        lumens:
          type: integer
          minimum: 0
          description: Light intensity measured in lumens.
        sentAt:
          $ref: "#/components/schemas/sentAt"
      sentAt:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```

#### Expected behavior
I expected  this:

```
public class LightMeasuredPayload {
    
    private @Valid int lumens;
    
    private @Valid java.time.LocalDateTime sentAt;
```

but I got this

```
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LightMeasuredPayload {

	public LightMeasuredPayload () {
	}
	public LightMeasuredPayload (
		Integer lumens, 
		String sentAt) {
		this.lumens = lumens;
		this.sentAt = sentAt;
	}


	private Integer lumens;
	private String sentAt;
```
SentAt field must be java.time.LocalDateTime type

### PR DESCRIPTION
**Pull request by blzsaa**
fix: Generate correct fields using both type and format part from data type formats

  **Description**
  * Reads both type and format of data type to generate java field from it,
following the logic below:

  | type    | format    | Java class     | fmt | sample                       |
  |---------|-----------|----------------|-----|------------------------------|
  | string  | date      | LocalDate      | %s  | 2000-12-31                   |
  | string  | date-time | OffsetDateTime | %s  | 2000-12-31T23:59:59+01:00    |
  | string  | byte      | byte[]         | %s  | U3dhZ2dlciByb2Nrcw==         |
  | string  | binary    | byte[]         | %s  | base64-encoded file contents |
  | string  | undefined | String         | %s  | string                       |
  | integer | int32     | Integer        | %d  | 1                            |
  | integer | int64     | Long           | %d  | 1L                           |
  | integer |           | Integer        | %d  | 1                            |
  | number  | float     | Float          | %f  | 1.1F                         |
  | number  | double    | Double         | %f  | 1.1                          |
  | number  |           | BigDecimal     | %s  | 100.1                        |
  | boolean |           | Boolean        | %s  | true                         |
  * In case of unknown format (e.g. type: string, format: email) it will generate
  default java class for given type (String).
  * See: https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#data-type-formats

  **Test**

-  Given _dataTypes.yaml_ with the following content:

  ```
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        $ref: '#/components/messages/lightMeasured'
    subscribe:
      operationId: updateLightMeasurement
      message:
        $ref: '#/components/messages/lightMeasured'
components:
  messages:
    lightMeasured:
      summary: Inform about environmental lighting conditions for a particular streetlight.
      payload:
        $ref: "#/components/schemas/lightMeasuredPayload"
  schemas:
    lightMeasuredPayload:
      type: object
      properties:
        integer:
          type: integer
          format: int32
        long:
          type: integer
          format: int64
        integerDefault:
          type: integer
        float:
          type: number
          format: float
        double:
          type: number
          format: double
        number:
          type: number
        stringEnum:
          type: string
          enum: [
              "userPassword"
          ]
        string:
          type: string
        byte:
          type: string
          format: byte
        binary:
          type: string
          format: binary
        boolean:
          type: boolean
        date:
          type: string
          format: date
        dateTime:
          type: string
          format: date-time
        password:
          type: string
          format: password
        email:
          type: string
          format: email
  ```

- when running: `ag dataTypes.yaml ./java-spring-cloud-stream-template`
- then LightMeasuredPayload.java should contains all generatable java fields, e.g. OffsetDateTime dateTime

  **Related issue(s)**
  Resolves #57

### CODE REVIEW

**Review by MichaelDavisSolace — APPROVED** [review]

**Comment by derberg** [comment]
@blzsaa

Hey, I introduced some linter fixes in the master that caused conflicts on your PR. I didn't want to ask you to fix it after such a long time waiting for merge of this PR. I took the liberty to fix those conflicts on my own + some additional liter issues. I checked against your example and generation passes, but I'm not sure if the result is what you expect. I think it is, as I tried to run it against the template from your initial commit and result was similar.

If you confirm all is good I will merge this one

**Comment by blzsaa** [comment]
Hi,
I checked and it generates the correct java file.

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
@all-contributors please add @blzsaa for code

**Comment by damaru-inc** [comment]
@blzsaa Thanks so much for the contribution. Just to let you know, soon I'll be adding a feature to deal with parameters in channel names.

**Pull request merged**
