### PR TITLE
feat: Migrate to the new template structure

### PR DESCRIPTION
**Pull request by fmvilas**
Moves all the template files inside the `template` folder.

See https://github.com/asyncapi/generator/pull/275

### Summary of changes

* Moved everything that should/might be copied to the output directory to its own directory: "template".
* Moved .hooks, .partials, and .filters to the root directory, outside "template". And renamed those as "hooks", "partials", and "filters".
* Got rid of special file names like `__README.md`. They are not conflicting anymore so they're now `README.md`.

### CODE REVIEW

**Comment by Mrc0113** [comment]
Something in this fix seemed to break the generator. I now get the error below, but if I point to my fork which doesn't have this PR merged it works fine. 

```
MJD-MacBook-Pro.local:/tmp/codegen3$ ag -p binder=solace -p artifactType=application -p artifactId=COVID19PopulationProvider2 -p groupId=com.solace.demo -p javaPackage=com.solace.demo.covid19 -p solaceSpringCloudVersion=1.0.0 -p springCloudStreamVersion=Horsham.SR3 -p springCloudVersion=Hoxton.SR3 ~/Downloads/COVID19PopulationProvider.yaml https://github.com/asyncapi/java-spring-cloud-stream-template.git
npm http fetch GET 304 https://registry.npmjs.org/lodash 144ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/js-yaml 148ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/esprima 48ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/argparse 69ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/sprintf-js 52ms (from cache)
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/codegen3/package.json'
npm WARN . No description
npm WARN . No repository field.
npm WARN . No README data
npm WARN . No license field.

+ @asyncapi/java-spring-cloud-stream-template@0.2.0
added 6 packages from 11 contributors in 2.082s
Something went wrong:
Template render error: (/private/tmp/codegen3/node_modules/@asyncapi/java-spring-cloud-stream-template/template/pom.app)
  Error: filter not found: groupId
    at Object._prettifyError (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:57:3)
    at Template.render (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:550:10)
    at Environment.renderString (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:378:17)
    at /usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:592:21
    at new Promise (<anonymous>)
    at Generator.renderString (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:591:12)
    at Generator.renderFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:616:19)
    at async Generator.generateFile (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:572:29)
    at async Walker.<anonymous> (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:444:13)
```

**Comment by fmvilas** [comment]
That's weird. It's not failing for me. Are you sure you're on the latest version of the generator, @Mrc0113?

**Comment by Mrc0113** [comment]
Ah okay that was it. I thought I had the most recent since I just installed it 2 days ago, but apparently you're moving fast :)

**Comment by fmvilas** [comment]
Yeah, sorry. We're trying to push all the breaking changes now as we want to release v1.0.0 soon: https://github.com/asyncapi/generator/milestone/4.

**Pull request merged**
