### PR TITLE
feat: use new generic filters

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- use generic filters library
- modify and cleanup of local filters for new testable style
- removed filters that are already in the generator-filters
- I also added eslint that we use in asyncapi as there was a lot of code to handle and formatting was very hard. Check out the new scripts that you can use in future, there are some errors I did not dig into that could not be fixed by eslint automatically

It looks like a lot of changes, but don't worry, I did not touch the logic. Some filters are removed but only because they are available thanks to the new generator-filter library

**Related issue(s)**
See also https://github.com/asyncapi/generator/issues/212

### CODE REVIEW

**Comment by damaru-inc** [comment]
I tested your branch. I got an error. In lib/ScsLib.js I require lodash, and that no longer works:

Error: There was a problem registering the hooks: Cannot find module 'lodash'
Require stack:
- /Users/michaeldavis/dev/sol/asynapi/templates/java-spring-cloud-stream-template/lib/ScsLib.js
- /Users/michaeldavis/dev/sol/asynapi/templates/java-spring-cloud-stream-template/hooks/post-process.js

**Comment by damaru-inc** [comment]
Running npm i in the template directory fixed the problem above.

**Comment by derberg** [comment]
@damaru-inc there should not be any issues with lodash. I tested and the generation works well. I'm just not able to test if the generated application works fine

The filter you are referring to is there. I looked twice to make sure no templates are lost
`https://github.com/asyncapi/java-spring-cloud-stream-template/pull/19/files#diff-c77b40961e3444aa670a27c018c4558eR291`

**Comment by derberg** [comment]
@damaru-inc from my side I'm ready to merge, how about you?

**Pull request merged**
